apiVersion: v1
kind: Pod
metadata:
  name: ztier
spec:
  containers:
  - name: ztier
    image: moabukar/zerotier:9ee0069
    env:
    - name: NETWORK_IDS
      valueFrom:
        configMapKeyRef:
          name: zerotier-networks
          key: NETWORK_IDS
    - name: ZTHOSTNAME
      valueFrom:
        configMapKeyRef:
          name: zerotier-networks
          key: ZTHOSTNAME
    - name: ZTAUTHTOKEN
      valueFrom:
        configMapKeyRef:
          name: zerotier-networks
          key: ZTAUTHTOKEN
    - name: AUTOJOIN
      valueFrom:
        configMapKeyRef:
          name: zerotier-networks
          key: AUTOJOIN
    securityContext:
      privileged: true
      capabilities:
        add:
        - NET_ADMIN
        - SYS_ADMIN
    volumeMounts:
    - name: dev-net-tun
      mountPath: /dev/net/tun
  volumes:
  - name: dev-net-tun
    hostPath:
      path: /dev/net/tun
      type: CharDevice
